### ISSUE TITLE
Multi-moderation commands

### ISSUE THREAD

**Issue by MrFluffy-BTE** [BuildTheEarth/main-bot#118]
suggestion: multi mod commands. 
Explanations:
=mmute [id, id, id...] reason 
=mwarn [id, ...] reason 
=mban same thing 
=mkick same thing

To help with multimuting and etc

Author: priceup#1789

**Comment by cAttte** [comment]
banning multiple people at the same time is done _very_ rarely by the moderators, and it's always because of raids, which would never result in anything lower than a ban anyways ("multimuting" is not a thing). they should just ban the members individually with their respective screenshots of proof. the addition of this feature would mean the addition of 4 useless commands and the addition of infrastructure (changes to [ActionLog](https://github.com/BuildTheEarth/main-bot/blob/main/src/entities/ActionLog.ts) and [TimedPunishment](https://github.com/BuildTheEarth/main-bot/blob/main/src/entities/TimedPunishment.ts)) to support this change (unless the command simply executed multiple punishments instead of making one "multi-punishment").
