### ISSUE TITLE
More helpful help command

### ISSUE THREAD

**Issue by mebrooks01** [BuildTheEarth/main-bot#82]
right now it just lists out all the commands you can use like 
```
avatar, catte, help, ping, snippets, suggest, suggestion, user
```
or 
Instead what it should be is like 
```
avatar: description here
catte: description here
help: description here
ping: description here
snippets: description here
suggest: description here
suggestion: description here
user: description here
```
this would make it much easier for someone to understand what all the commands do.

**Comment by arc25275** [comment]
Also making it clear that you can do `=help <command>` would be nice, as I have seen lots of people doing it the other way around.

**Comment by XboxBedrock** [comment]
well =help <name of command> exists

**Comment by XboxBedrock** [comment]
wait nvm arc beat me to it

**Comment by cAttte** [comment]
smh (shaking my head)

**Comment by cAttte** [comment]
also i was planning on making the command handler detect a `help` argument after the command name so you could run commands like `=suggestion help` which is what arc said

**Comment by HPaulson** [comment]
This should be fairly simple by expanding on the current structure:
```
    name: "ban",
    aliases: [],
    description: "Ban a member.",
    permission: [Roles.MODERATOR, Roles.MANAGER],
    usage: "<member> <length> <image URL | attachment> <reason>",
```

As all of this information is already available in the command class; Since you're using a collection for the commands, you could simply get whatever argument from the help page, such as `=help yeet` would attempt to get `yeet` from the collection, and return its results (displaying an err obviously if unexisting). If just `=help` is used, you can have a simple embed displaying said information using reactionCollectors to move pages. Additionally, a feature I enjoy to implement in help pages which is quite useful, you could check the author's permissions and only display commands they have access to. Here's an [example](https://github.com/HPaulson/SoB-The-Bot/blob/master/src/commands/help.ts) of this implementation from one of my older projects.

**Comment by cAttte** [comment]
the help command already has the features you described (except for pagination, which shouldn't be necessary). and the `help` argument would exist along with the existing `help` command. i've thought about argument conflicts, but i can't think of any commands in which you'd need to use "help" as a legit argument (apart from an `echo` command, which doesn't exist). this shouldn't be confusing since it will be a hidden "fool-proofing" feature

**Comment by arc25275** [comment]
I’m sure catte knows how to get details from a structure that he wrote, but good ideas nonetheless :)

**Comment by HPaulson** [comment]
> the help command already has the features you described (except for pagination, which shouldn't be necessary). and the `help` argument would exist along with the existing `help` command. i've thought about argument conflicts, but i can't think of any commands in which you'd need to use "help" as a legit argument (apart from an `echo` command, which doesn't exist). this shouldn't be confusing since it will be a hidden "fool-proofing" feature

While this is valid *now*, it is definitely possible in the future that this argument could create conflicts; Never the less, using the command name as an argument for the help command is generally the more known & common practice. Additionally, my suggestion above makes mention to displaying this data on the help command itself, rather than forcing a user to use the argument at all, since that can get very- very tedious (Would also solve initial issue's comment).
